// Static assets published unchanged into dist/ — everything the site serves
// that isn't generated by build.mjs/bundle-js.mjs from src/.
//
// Deliberately NOT here (and so NOT published):
//   - client/app.js            — unused; src/client/ is the real source
//   - headshot-*.jpg (root)    — unoptimized originals; the served images are
//                                 the resized/webp variants in images/headshots/
//   - styles.css               — build input only, inlined into <head>, never
//                                 requested as a standalone URL
//   - about.html/contact.html/services.html/schedule/ (root) — handled by
//                                 the redirect rules in HOST_CONFIG_FILES instead
//
// Paths are relative to the repo root. Directories are copied recursively.
export const STATIC_ASSET_PATHS = [
  'apple-touch-icon.png',
  'favicon-16x16.png',
  'favicon-32x32.png',
  'favicon-48x48.png',
  'favicon.png',
  'favicon.svg',
  'icon-192.png',
  'icon-512.png',
  'site.webmanifest',
  'robots.txt',
  'sitemap.xml',
  'Resume-David-Dangerfield.pdf',
  'LinkedIn-Profile.pdf',
  'fonts',
  'images',
]

// Hosting-provider config files. Each provider requires its own exact
// filenames at the published root (Cloudflare Pages needs `_headers` /
// `_redirects` there, for instance) — so the source of truth lives in a
// folder named for the provider, and this list is the one place that maps
// it to what actually gets published. Swapping providers means adding a
// new named folder, pointing this list at it, and removing the old one —
// nothing else in the build changes.
export const HOST_CONFIG_FILES = [
  { from: 'cloudflare/_headers', to: '_headers' },
  { from: 'cloudflare/_redirects', to: '_redirects' },
]
